on: ["push", "pull_request"]

name: main workflow

env:
  ETHERSCAN_TOKEN: ${{ secrets.ETHERSCAN_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WEB3_INFURA_PROJECT_ID: ${{ secrets.WEB3_INFURA_PROJECT_ID }}

  # increasing available memory for node reduces issues with ganache crashing
  # https://nodejs.org/api/cli.html#cli_max_old_space_size_size_in_megabytes
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npx hardhat test
